package com.block.storage.message;

public enum MessageType {
    ADD_PEER_MESSAGE, NETWORK_INFO_MESSAGE, SAVE_FILE_MESSAGE, RETRIEVE_FILE_MESSAGE, RETRIEVE_FILE_RESPONSE_MESSAGE, OK_MESSAGE, FAIL_MESSAGE
}

